global:
  scrape_interval: 15s # How frequently to scrape targets
  evaluation_interval: 15s # How frequently to evaluate rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100'] # Prometheus can scrape Loki's metrics

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000'] # Prometheus can scrape Grafana's metrics

  - job_name: 'laravel_app_metrics'
    metrics_path: /metrics # Default endpoint for Prometheus PHP client
    static_configs:
      - targets: ['laravel.test:80'] # Or whatever port your app exposes metrics on